---
title: "Project Title"
subtitle: "DA5030 Intro to Machine Learning & Data Mining"
author: 
  - "Clare Wolfendale"
  - "Wolfendale.C@husky.neu.edu"
  - "Fall 2018 Signature Assignment"
date: "December 9, 2018"
subparagraph: true
output: pdf_document
documentclass: report
fontsize: 12pt
urlcolor: blue
geometry:
  - margin=0.7in
---

```{r libs}
library(tidyverse)
library(assertr)
library(knitr)
library(e1071)
library(C50)
library(gmodels)
```

## Introduction

## Buisness Understanding

## Data Understanding

```{r read_in}
raw_data <- read.csv(
    "risk_factors_cervical_cancer.csv",
    strip.white = TRUE,
    na.strings  = "?",
    col.names   = c(
        "age",
        "n_sexual_partners",
        "age_first_sexual_intercourse",
        "n_pregnancies",
        "smokes",
        "n_years_smokes",
        "n_packs_per_year",
        "hormonal_contraceptives",
        "n_years_hormonal_contraceptives",
        "iud",
        "n_years_iud",
        "std",
        "n_stds",
        "std_condylomatosis",
        "std_cervical_condylomatosis",
        "std_vaginal_condylomatosis",
        "std_vulvo_perineal_condylomatosis",
        "std_syphilis",
        "std_pelvic_inflammatory_disease",
        "std_genital_herpes",
        "std_molluscum_contagiosum",
        "std_aids",
        "std_hiv",
        "std_hepatitis_b",
        "std_hpv",
        "n_std_diagnosis",
        "n_years_since_first_std",
        "n_years_since_last_std",
        "prev_dx_cancer",
        "prev_dx_cin",
        "prev_dx_hpv",
        "prev_dx",
        "hinselmann",
        "schiller",
        "citology",
        "biopsy"  
    )
)
str(raw_data)
```

```{r n_miss}
sapply(raw_data, function(x) sum(is.na(x)))
```

## Data Preparation

```{r target_var}
raw_data <- raw_data %>% 
    rowwise() %>% 
    mutate(cancer = max(biopsy, hinselmann, schiller, citology)) %>% 
    ungroup() %>% 
    select(-biopsy, -hinselmann, -schiller, -citology)

# convert to factor variable
raw_data$cancer <- factor(raw_data$cancer, levels = c(0,1), labels = c("no", "yes"))

table(raw_data$cancer)
```

```{r zscore}
standardize <- function(x) {
    return ((x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE))
}
```


```{r find_outliers}
cont_vars <- c(
    "age",
    "n_sexual_partners",
    "age_first_sexual_intercourse",
    "n_pregnancies",
    "n_years_smokes",
    "n_packs_per_year",
    "n_years_hormonal_contraceptives",
    "n_years_iud",
    "n_stds",
    "n_std_diagnosis",
    "n_years_since_first_std",
    "n_years_since_last_std"
)

# create z-scores for continuous variables
raw_z <- as.data.frame(
    lapply(
        raw_data[, cont_vars], 
        standardize
    )
)
```

```{r examine_outliers}
kable(table(raw_data$n_pregnancies),   col.name = c("n_pregnancies",  "Freq"))
summary(raw_z$n_pregnancies)

kable(table(raw_data$n_std_diagnosis), col.name = c("n_std_diagnosis","Freq"))
summary(raw_z$n_std_diagnosis)

summary(raw_data$age)
summary(raw_z$age)

raw_z %>% 
    mutate_all(funs(ifelse(abs(.) > 8, 1, 0))) %>% 
    summarize_all(sum, na.rm = TRUE) %>% 
    gather(key = variable, value = n_outliers) %>% 
    kable()
```

```{r elim_outliers}
raw_z <- as.data.frame(
    lapply(
        raw_z, 
        function(x) ifelse(abs(x) > 8, NA, x)
    )
)

dx_data <- raw_data

dx_data[which(is.na(raw_z$n_pregnancies)),   ]$n_pregnancies   <- NA
dx_data[which(is.na(raw_z$n_years_smokes)),  ]$n_years_smokes  <- NA
dx_data[which(is.na(raw_z$n_years_iud)),     ]$n_years_iud     <- NA
dx_data[which(is.na(raw_z$n_std_diagnosis)), ]$n_std_diagnosis <- NA
```


```{r binary_vars}
dx_data %>% 
    assert(in_set(0, 1, NA), -one_of(c(cont_vars,"cancer")), success_fun = success_logical)
```

```{r drop_vars}
miss_rates <- as.data.frame(
    lapply(
        dx_data, 
        function(x) round(100*mean(is.na(x), digits = 1))
    )
)

drop_vars <- miss_rates %>% 
    gather(key = variable, value = miss_rate) %>% 
    filter(miss_rate > 15) %>% 
    select(variable)

drop_vars

dx_data <- dx_data %>% 
    select(-one_of(drop_vars$variable))

str(dx_data)
```

```{r impute_fun}
impute_var <- function(var) {
    # calculates median of variable
    med <- round(median(var, na.rm = TRUE), 0)
    
    # imputes missing values with median
    var[is.na(var)] <- med
    
    return(var)
}
```

```{r impute_vars}
# store target variable separately
dx_labels <- dx_data$cancer

dx_data <- as.data.frame(
    lapply(
        dx_data[, !names(dx_data) %in% c("cancer")], 
        impute_var
    )
)

# confirm no more missing values
sapply(dx_data, function(x) sum(is.na(x)))

vars <- colnames(dx_data)

dx_data %>% 
    assert(not_na, one_of(vars), success_fun = success_logical)
```

```{r bin_age}
bayes_data <- dx_data

bayes_data$age_bin[bayes_data$age > 0  & bayes_data$age <= 20] <- 1
bayes_data$age_bin[bayes_data$age > 20 & bayes_data$age <= 30] <- 2
bayes_data$age_bin[bayes_data$age > 30 & bayes_data$age <= 40] <- 3
bayes_data$age_bin[bayes_data$age > 41                       ] <- 4

bayes_data$age_fac <- factor(
    bayes_data$age_bin, 
    levels = c(1,2,3,4), 
    labels = c("lt 20", "21 to 30", "31 to 40", "gt 40")
)
table(bayes_data$age_fac)
```

```{r bin_n_partners}
bayes_data$n_sexual_partners_bin[bayes_data$n_sexual_partners <= 3] <- 1
bayes_data$n_sexual_partners_bin[bayes_data$n_sexual_partners  > 3] <- 2

bayes_data$n_sexual_partners_fac <- factor(
    bayes_data$n_sexual_partners_bin, 
    levels = c(1,2), 
    labels = c("lt 3", "gt 3")    
)

table(bayes_data$n_sexual_partners_fac)
```

```{r bin_age_first_sex}
bayes_data$age_first_sexual_intercourse_bin[bayes_data$age_first_sexual_intercourse <= 15] <- 1
bayes_data$age_first_sexual_intercourse_bin[bayes_data$age_first_sexual_intercourse == 16] <- 2
bayes_data$age_first_sexual_intercourse_bin[bayes_data$age_first_sexual_intercourse == 17] <- 3
bayes_data$age_first_sexual_intercourse_bin[bayes_data$age_first_sexual_intercourse == 18] <- 4
bayes_data$age_first_sexual_intercourse_bin[bayes_data$age_first_sexual_intercourse >= 19] <- 5

bayes_data$age_first_sexual_intercourse_fac <- factor(
    bayes_data$age_first_sexual_intercourse_bin, 
    levels = c(1,2,3,4,5), 
    labels = c("lt 15", "16", "17", "18", "gt 19")    
)

table(bayes_data$age_first_sexual_intercourse_fac)
```

```{r bin_n_preg}
bayes_data$n_pregnancies_bin[bayes_data$n_pregnancies == 0] <- 1
bayes_data$n_pregnancies_bin[bayes_data$n_pregnancies == 1] <- 2
bayes_data$n_pregnancies_bin[bayes_data$n_pregnancies == 2] <- 3
bayes_data$n_pregnancies_bin[bayes_data$n_pregnancies == 3] <- 4
bayes_data$n_pregnancies_bin[bayes_data$n_pregnancies >= 4] <- 5

bayes_data$n_pregnancies_fac <- factor(
    bayes_data$n_pregnancies_bin, 
    levels = c(1,2,3,4,5), 
    labels = c("0", "1", "2", "3", "4+")    
)

table(bayes_data$n_pregnancies_fac)
```

```{r bin_years_smoke}
bayes_data$n_years_smokes_bin[bayes_data$n_years_smokes == 0                                  ] <- 1
bayes_data$n_years_smokes_bin[bayes_data$n_years_smokes >  0 & bayes_data$n_years_smokes <= 10] <- 2
bayes_data$n_years_smokes_bin[bayes_data$n_years_smokes > 10                                  ] <- 3


bayes_data$n_years_smokes_fac <- factor(
    bayes_data$n_years_smokes_bin, 
    levels = c(1,2,3), 
    labels = c("0 years", "1-10 years", "10+ years")    
)

table(bayes_data$n_years_smokes_fac)
```

```{r bin_n_packs}
bayes_data$n_packs_per_year_bin[bayes_data$n_packs_per_year == 0                                  ] <- 1
bayes_data$n_packs_per_year_bin[bayes_data$n_packs_per_year > 0 & bayes_data$n_packs_per_year <= 2] <- 2
bayes_data$n_packs_per_year_bin[bayes_data$n_packs_per_year > 2 & bayes_data$n_packs_per_year <= 5] <- 3
bayes_data$n_packs_per_year_bin[bayes_data$n_packs_per_year > 5                                   ] <- 4

bayes_data$n_packs_per_year_fac <- factor(
    bayes_data$n_packs_per_year_bin, 
    levels = c(1,2,3,4), 
    labels = c("0 per year", "1-2 per year", "2-5 per year", "5+ per year")    
)

table(bayes_data$n_packs_per_year_fac)
```

```{r bin years_contra}
bayes_data$n_years_hc_bin[bayes_data$n_years_hormonal_contraceptives == 0                                                 ] <- 1
bayes_data$n_years_hc_bin[bayes_data$n_years_hormonal_contraceptives > 0 & bayes_data$n_years_hormonal_contraceptives <= 2] <- 2
bayes_data$n_years_hc_bin[bayes_data$n_years_hormonal_contraceptives > 2 & bayes_data$n_years_hormonal_contraceptives <= 5] <- 3
bayes_data$n_years_hc_bin[bayes_data$n_years_hormonal_contraceptives > 5                                                  ] <- 4

bayes_data$n_years_hc_fac <- factor(
    bayes_data$n_years_hc_bin, 
    levels = c(1,2,3,4), 
    labels = c("0 years", "1-2 years", "2-5 years", "5+ years")    
)

table(bayes_data$n_years_hc_fac)
```

```{r bin_years_iud}
bayes_data$n_years_iud_bin[bayes_data$n_years_iud > 0 & bayes_data$n_years_iud <= 1] <- 1
bayes_data$n_years_iud_bin[bayes_data$n_years_iud > 1 & bayes_data$n_years_iud <= 2] <- 2
bayes_data$n_years_iud_bin[bayes_data$n_years_iud > 2 & bayes_data$n_years_iud <= 3] <- 3
bayes_data$n_years_iud_bin[bayes_data$n_years_iud > 3                              ] <- 4

bayes_data$n_years_iud_fac <- factor(
    bayes_data$n_years_iud_bin, 
    levels = c(1,2,3,4), 
    labels = c("0-1 years", "1-2 years", "2-3 years", "4+ years")    
)

table(bayes_data$n_years_iud_fac)
```

```{r drop_cont_vars}
drop_vars <- c(
    "age",
    "age_bin",
    "n_sexual_partners",
    "n_sexual_partners_bin",
    "age_first_sexual_intercourse",
    "age_first_sexual_intercourse_bin",
    "n_pregnancies",
    "n_pregnancies_bin",
    "n_years_smokes",
    "n_years_smokes_bin",
    "n_packs_per_year",
    "n_packs_per_year_bin",
    "n_years_hormonal_contraceptives",
    "n_years_hc_bin",
    "n_years_iud",
    "n_years_iud_bin"
)


bayes_data <- bayes_data %>% 
    select(-one_of(drop_vars))
```

```{r partition}
n_train_obs <- floor(0.80*nrow(dx_data))

# set a seed number
set.seed(123456789)

# select 900 row indexes at random
train_sample <- sample(nrow(dx_data), n_train_obs)
head(train_sample)

dt_train <- dx_data[ train_sample, ]
dt_test  <- dx_data[-train_sample, ]

glm_train <- cbind(dt_train, cancer = dx_labels[ train_sample])
glm_test  <- cbind(dt_test,  cancer = dx_labels[-train_sample])

nb_train <- dx_data[ train_sample, ]
nb_test  <- dx_data[-train_sample, ]

train_labels <- dx_labels[ train_sample]
test_labels  <- dx_labels[-train_sample]
```

## Modeling

### Naive Bayes

```{r train_nb}
nb_classifier <- naiveBayes(nb_train, train_labels)
nb_classifier <- naiveBayes(nb_train, train_labels, laplace = 1)
nb_test_pred <- predict(nb_classifier, nb_test)

CrossTable(
    test_labels, 
    nb_test_pred,
    prop.chisq = FALSE, 
    prop.c     = FALSE, 
    prop.r     = FALSE,
    dnn = c('actual dx', 'predicted dx')
)
```

### Decision Tree

```{r train_dtree}
dt_classifier <- C5.0(dt_train, train_labels)
summary(dt_classifier)

dt_classifier <- C5.0(dt_train, train_labels, trials = 10)
dt_classifier

dt_test_pred <- predict(dt_classifier, dt_test)

CrossTable(
    test_labels, 
    dt_test_pred,
    prop.chisq = FALSE, 
    prop.c     = FALSE, 
    prop.r     = FALSE,
    dnn = c('actual dx', 'predicted dx')
)
```

## Evaluation


## Deployment

